name: Database Operations

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run operations on'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      operation:
        description: 'Database operation to perform'
        required: true
        default: 'migrate'
        type: choice
        options:
        - migrate
        - seed
        - reset

jobs:
  database:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma client
      run: npm run db:generate

    - name: Run database migration
      if: github.event.inputs.operation == 'migrate'
      run: npm run db:migrate
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Seed database
      if: github.event.inputs.operation == 'seed'
      run: npm run db:seed
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Reset database
      if: github.event.inputs.operation == 'reset'
      run: |
        npx prisma migrate reset --force
        npm run db:seed
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Verify database connection
      run: npx prisma db pull
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
